// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed iride.ico
var ResourceIrideIcoData []byte
var ResourceIrideIco = &fyne.StaticResource{
	StaticName:    "iride.ico",
	StaticContent: ResourceIrideIcoData,
}
